GET http://localhost:4000/api/cars

###

POST http://localhost:4000/api/cars

###

PATCH http://localhost:4000/api/cars/6579b581d10bff0f620c932a
Content-Type: application/json

{
  "wins": 0
}


###

DELETE http://localhost:4000/api/cars/6565ac22aa7f2e525eaf9d89

###

GET http://localhost:4000/api/cars/mid

###
GET http://localhost:4000/api/drivers


###
GET http://localhost:4000/api/cars/65686a17d03223342bb87d73


